import Head from "next/head";
import React from "react";
import styles from "./index.module.css";

export default function Butter() {
  return (
    <>
      <Head>
        <title>Butter - 一个习惯追踪app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`min-h-screen ${styles.butterPage}`}>
        <header className="px-6 lg:px-12 mb-12 py-9 flex justify-between items-center text-white ">
          <a className={`${styles.icon}`}>Butter</a>
          <nav className="flex" aria-label="Main">
            <a
              className={`text-d-p-sm mx-2 sm:mx-4 last:mr-0 opacity-80 hover:opacity-100 font-semibold `}
            >
              更新日志
            </a>
            <a
              className={`text-d-p-sm mx-2 sm:mx-4 last:mr-0 opacity-80 hover:opacity-100 font-semibold `}
            >
              关于作者
            </a>
            <a
              className={`text-d-p-sm mx-2 sm:mx-4 last:mr-0 opacity-80 hover:opacity-100 font-semibold `}
            >
              下载
            </a>
          </nav>
        </header>
        <main className=" ">
          <section className={`flex `}>
            <div className={`w-1/2 lg:max-w-2xl lg:mx-auto`}>
              <h2 className="font-display text-m-h1  text-white  text-6xl leading-normal ">
                <span style={{ color: "#0ea5e9" }}>Butter</span> 只专注记录你的
                <span style={{ color: "#5eead4" }}> 习惯</span> 并且有
                <span style={{ color: "#fbbf24" }}> 更好的记录方式 </span>
                让你能更清晰的
                <span style={{ color: "#f43f5e" }}> 看清自己</span>
              </h2>
              <p
                className="text-m-p-lg mt-2 pr-4 lg:text-d-p-lg"
                style={{ color: "rgb(208, 208,208)" }}
              >
                Butter
                一款简洁的习惯记录App，它只做一件事记录习惯，没有社区，没有广告，没有乱七八糟的功能。
                并且Butter是开源作品，任何人都可以基于开源的代码进行创作。
                也许Butter是最适合你的习惯App。
              </p>
            </div>
            <div
              className={`w-1/2 p-4 rounded ${styles.appDisplay}`}
              // style={{
              //   background:
              //     "linear-gradient(to right, rgb(238, 156, 167), rgb(255, 221, 225))",
              // }}
            >
              <img
                style={{ height: 600 }}
                src="https://files.catbox.moe/4x3bv5.png"
              ></img>
            </div>
          </section>
        </main>
      </main>
    </>
  );
}
